name: Deploy React + Vite to Github Pages

on:
  workflow_dispatch:
  push:
    branches: ['gh-pages']

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Nodejs
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      # Install Dependecies
      - name: Install Dependecies
        run: npm install

      # Build the Project
      - name: Build Project
        run: npm run build 

      # Deploy to Gihub Pages
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist